# ---- Config ----

branches:
  only: [master, staging, maintenance]
language: generic
sudo: required
services:
  - docker
env:
  - CF_FRONTEND_IMAGE=registry.gitlab.com/captainfact/captain-fact-frontend:$TRAVIS_BRANCH

# ---- Jobs ----
script: docker build --build-arg BUILD_ENV=$TRAVIS_BRANCH -t $CF_FRONTEND_IMAGE .

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.gitlab.com;
    echo "Pushing $CF_FRONTEND_IMAGE" && docker push $CF_FRONTEND_IMAGE;
    fi
