name: E2E/Integration tests

on: [push]

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Restore .npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-npm-cache-
      - name: Install dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit
      - name: Start local API
        run: docker-compose up -d
      - name: Start Frontend
        run: npm start &
      - name: Waiting for Frontend to be ready
        run: until curl -s localhost:3333 > /dev/null; do sleep 1; done
      - name: Waiting for API to be ready
        run: until curl localhost:4000; do sleep 1; done
      - name: Run tests
        run: npm run cypress -- --record
      - name: Shutdown Frontend
        run: kill $(jobs -p) || true
      - name: Shutdown API
        run: docker-compose down
